query BillingStatus {
  billing {
    features {
      allowDiskUse
      useCustomIntegrations
    }
    stripe_customer_id
    stripe_subscription_id
    subscription_last_payment
    subscription_active
  }
}
