query ProfilesFieldDescriptions {
  configuration {
    apps {
      profiles {
        fieldDescriptions {
          name
          email
          phone
          twitter
          biography
          title
        }
      }
    }
  }
}
