query ServiceUsage($month: Int, $year: Int) {
  billing {
    usage {
      api(month: $month, year: $year) {
        billable
        total
        since
      }
      storage {
        database
        files
      }
    }
  }
}
