query UsersList($page: Int, $limit: Int!) {
  users(page: $page, limit: $limit, sort: "{ \"_id\": 1 }") {
    docs {
      _id
      name
      s: slug
      u: username
      e: email
      r: retired
      c: current_title
    }
  }
}
