name: 'Release Tauri app'

on:
  push:
    branches:
      - tauri

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm ci
        env:
          NPM_GH_PASS: ${{ secrets.NPM_GH_PASS }}

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: --max-old-space-size=8128
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_AUTH_BASE_URL: ${{ secrets.VITE_AUTH_BASE_URL }}
          VITE_HOCUSPOCUS_BASE_URL: ${{ secrets.VITE_HOCUSPOCUS_BASE_URL }}
          VITE_API_PROTOCOL: ${{ secrets.VITE_API_PROTOCOL }}
          VITE_WS_PROTOCOL: ${{ secrets.VITE_WS_PROTOCOL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: ''
          releaseDraft: true
          prerelease: false
          tauriScript: 'npm run tauri'
